### ISSUE TITLE
vdr: can't access video directory /srv/vdr/video

### ISSUE THREAD

**Issue by bernhardberger** [tunip/docker-vdr#1]
Hi,

after my last windows system in my network running DVBViewer broke down today I'm taking the change and moved everything on a linux machine.

However, I have no clue on how to initially configure VDR to get it running. I have no other options as I have a DD Octopus Twin CI and 2 DuoFlex S2 (v5 and v6) in my system and I depend on MTD (ORF, Sky, HDAustria smartcards...).

Can you give me some hints on how to get started? I already installed the latest DD drivers (0.93 at the time of my writing)

I'm a webdev and sysadmin and have good Linux (debian/ubuntu) knowledge and know how to use docker, I just can't figure out what to do with VDR as the documentation is severely lacking.

My docker-compose.yml:

```yml
  vdr:
    container_name: vdr
    image: tunip/vdr
    ports:
      - 2004:2004
      - 3000:3000
      - 6419:6419
      - 34891:34891
      - 34892:34892
    devices:
      - /dev/dvb
    volumes:
      - $CONFIG_DIR/vdr/etc:/etc/vdr
      - $CONFIG_DIR/vdr/config:/var/lib/vdr
      - $CONFIG_DIR/vdr/data:/data
      - $STORAGE_DIR/livetv/recordings:/recordings
    restart: unless-stopped
```

**Comment by tunip** [comment]
Hi,

I have the initial config files on my todo list.

Will give you now a short description for starting this container.
Later I put the initial config files into the image and copy it on first start.

Hope that helps you to start this vdr container.

1. Here my docker-compose-yml. I use macvlan for all of my containers. You can, of course, use your ports above, thats fine.
```
  vdr:
    image: tunip/vdr:latest
    restart: unless-stopped
    networks:
      macvlan:
        ipv4_address: 192.168.9.78
    logging:
      driver: "journald"
    environment:
      - "TZ=Europe/Berlin"
    volumes:
      - /var/appdata/vdr/etc:/etc/vdr
      - /var/appdata/vdr/config:/var/lib/vdr
      - /var/appdata/vdr/data:/data
      - /mnt/storage/recordings:/recordings
      - /tmp:/timeshift
```
Timeshift volume is only needed for the robotv plugin to minimize disk (ssd) write activity, because it is a ring buffer during live tv. /tmp is on my system a ram disk.

2. The /etc/vdr directory
content:
```
/vdr/etc$ ls -la
drwxrwxr-x 2 duser users 4096 Sep 15 16:44 conf.avail
drwxrwxr-x 2 duser users 4096 Nov 29 22:22 conf.d
```

ls conf.avail
```
10-ddci2.conf
20-dvbapi.conf
30-satip.conf
50-epgsearch.conf
50-robotv.conf
50-streamdev-server.conf
50-vnsiserver.conf
```

ls conf.d
```
00-vdr.conf
10-ddci2.conf -> ../conf.avail/10-ddci2.conf
20-dvbapi.conf -> ../conf.avail/20-dvbapi.conf
30-satip.conf -> ../conf.avail/30-satip.conf
50-epgsearch.conf -> ../conf.avail/50-epgsearch.conf
50-robotv.conf -> ../conf.avail/50-robotv.conf
50-streamdev-server.conf -> ../conf.avail/50-streamdev-server.conf
```

And the content of 00-vdr.conf:
```
[vdr]
--chartab=ISO-8859-15
--port=6419
--log=2
--video=/recordings
--cachedir=/data
--filesize=1T
```

Content of 10-ddci2.conf:
```
[ddci2]
#--ignact
#    ignore active flag; speeds up channel switching to decryted channels

#--bufsz
#    CAM receive/send buffer size in packets a 188 bytes
#    (default: 1500, max: 10000)

#--clrsct
#     clear the scambling control bit before the packet is send to VDR

--loglevel=2
#     0/1/2/3 log nothing/error/info/debug

#--debugmask
#    Bitmask to enable special debug logging
#        0x0001 ... all what the developer thought should be logged in debug default
#        0x0002 ... file access during init
#        0x0400 ... CAM data read/write access (heavy logging)
#        0x0800 ... Scrambling control
#        0x1000 ... CAM buffer statistic (quite much logging)

#--sleeptimer
#    CAM receive/send/deliver thread sleep timer in ms
#    (default: 100, max: 1000)
```

Content of 20-dvbapi.conf:
```
[dvbapi]

```

Content of 30-satip.conf:
```
[satip]
-d 8
-s 192.168.9.18|DVBS2-8|OctopusNet
#-p 34000-34009
#-t 1

```

Content of 50-epgsearch.conf:
```
[epgsearch]

```

Content of 50-streamdev-server.conf:
```
[streamdev-server]

```

Content of 50-robotv.conf:
```
[robotv]

```
